<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>

    <!-- NuGet package metadata -->
    <PackageId>Mamba</PackageId>
    <Description>TODO: Add package description</Description>
    <Authors>TODO: Add authors</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/TODO/mamba</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TODO/mamba.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>aspnetcore</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
